kind: Service
apiVersion: v1
metadata:
  name: jupyterhub
  namespace: spark-project
spec:
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30002
  selector:
    component: spark-master
  type: NodePort