apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.8
    path: "/exports/data/gurvinder.singh@uninett.no/files/notebooks"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebooks-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi