apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-worker-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.8
    path: "/exports/data/gurvinder.singh@uninett.no/files/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-worker-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi