kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-driver-controller
spec:
  replicas: 1
  selector:
    component: spark-driver
  template:
    metadata:
      labels:
        component: spark-driver
    spec:
      containers:
        - name: spark-worker
          image: gurvin/spark-driver
          ports:
            - containerPort: 4040
          resources:
            requests:
              cpu: 100m
