apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hdfs-datanode
spec:
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      nodeSelector:
        datanode: "true"
      containers:
      - name: hdfs-datanode
        image: gurvin/hdfs-datanode:v2.7.2
        ports:
        - containerPort: 50010
        - containerPort: 50020
        - containerPort: 50075
        - containerPort: 50475
        resources:
          requests:
            cpu: 1048m
